"""
Runtime Key Manager - Handles API key input when bot starts
"""
import os
import sys
import json
from pathlib import Path
import getpass
from typing import Dict, Optional

class RuntimeKeyManager:
    """Manages API keys at runtime"""
    
    def __init__(self):
        self.keys = {}
        self.env_file = Path('.env')
        self.secrets_file = Path('config/secrets.json')
        
    def check_existing_keys(self) -> bool:
        """Check if keys already exist"""
        # Check .env file
        if self.env_file.exists():
            print("✅ Found existing configuration in .env file")
            return True
        
        # Check environment variables
        if os.getenv('BINANCE_API_KEY'):
            print("✅ Found API keys in environment variables")
            return True
        
        return False
    
    def ask_for_keys_interactive(self):
        """Ask for API keys interactively"""
        print("\n" + "=" * 60)
        print("🔑 API KEY SETUP REQUIRED")
        print("=" * 60)
        
        keys = {}
        
        # Binance
        print("\n📊 BINANCE API SETUP:")
        print("1. Visit: https://www.binance.com/en/my/settings/api-management")
        print("2. Create API key with Spot & Margin permissions")
        print("3. Enter keys below:\n")
        
        use_binance = input("Use Binance API? (y/n): ").lower() == 'y'
        if use_binance:
            keys['BINANCE_API_KEY'] = input("Binance API Key: ").strip()
            keys['BINANCE_API_SECRET'] = getpass.getpass("Binance API Secret: ")
        
        # Database
        print("\n💾 DATABASE SETUP (Optional):")
        use_db = input("Setup database? (y/n): ").lower() == 'y'
        if use_db:
            keys['DATABASE_HOST'] = input("Database Host [localhost]: ").strip() or "localhost"
            keys['DATABASE_PORT'] = input("Database Port [5432]: ").strip() or "5432"
            keys['DATABASE_NAME'] = input("Database Name [forex_bot]: ").strip() or "forex_bot"
            keys['DATABASE_USER'] = input("Database User [forex_user]: ").strip() or "forex_user"
            keys['DATABASE_PASSWORD'] = getpass.getpass("Database Password: ")
        
        # Telegram
        print("\n📱 TELEGRAM NOTIFICATIONS (Optional):")
        use_telegram = input("Setup Telegram? (y/n): ").lower() == 'y'
        if use_telegram:
            print("\n1. Talk to @BotFather on Telegram")
            print("2. Create bot with /newbot")
            print("3. Get bot token")
            keys['TELEGRAM_BOT_TOKEN'] = input("Telegram Bot Token: ").strip()
            keys['TELEGRAM_CHAT_ID'] = input("Telegram Chat ID: ").strip()
        
        # Save to .env
        self.save_to_env(keys)
        return keys
    
    def save_to_env(self, keys: Dict[str, str]):
        """Save keys to .env file"""
        env_content = []
        
        # Add standard config
        env_content.append("# Forex Trading Bot Configuration")
        env_content.append("# Auto-generated by RuntimeKeyManager")
        env_content.append("")
        
        # Add keys
        for key, value in keys.items():
            env_content.append(f"{key}={value}")
        
        # Add defaults
        env_content.append("\n# Default settings")
        env_content.append("ENVIRONMENT=development")
        env_content.append("DEBUG=true")
        env_content.append("LOGGING_LEVEL=INFO")
        
        # Write file
        with open(self.env_file, 'w') as f:
            f.write('\n'.join(env_content))
        
        # Set secure permissions
        self.env_file.chmod(0o600)
        
        print(f"\n✅ Configuration saved to {self.env_file}")
        print("⚠️  Keep this file secure! Never commit to version control.")
    
    def load_keys(self) -> Dict[str, str]:
        """Load keys from .env or ask for them"""
        if not self.check_existing_keys():
            print("\n📝 No existing API keys found.")
            return self.ask_for_keys_interactive()
        
        # Load from .env
        keys = {}
        if self.env_file.exists():
            with open(self.env_file, 'r') as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith('#'):
                        if '=' in line:
                            key, value = line.split('=', 1)
                            keys[key.strip()] = value.strip()
        
        # Also load from environment
        for key in ['BINANCE_API_KEY', 'BINANCE_API_SECRET', 
                   'DATABASE_PASSWORD', 'TELEGRAM_BOT_TOKEN']:
            env_value = os.getenv(key)
            if env_value:
                keys[key] = env_value
        
        return keys
    
    def get_key(self, key_name: str) -> Optional[str]:
        """Get specific key"""
        return self.keys.get(key_name)